---
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Validate Nginx Configuration
  ansible.builtin.command:
    cmd: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
  when: nginx_service_state == "started"
